<script setup lang="ts">
definePageMeta({ layout: 'default' })
useSeoMeta({ title: 'Terms of Service — RentCred' })
</script>

<template>
  <div>
    <!-- Hero -->
    <section class="bg-[#0D0D0D]">
      <div class="max-w-[1440px] mx-auto px-5 sm:px-8 lg:px-20 py-10 lg:py-16 flex flex-col items-center gap-4">
        <span class="font-mono text-[11px] font-semibold text-[#FF8400] tracking-[2px]">LEGAL</span>
        <h1 class="font-mono text-[28px] sm:text-[34px] lg:text-[40px] font-medium text-white text-center" style="letter-spacing: -1px">Terms of Service</h1>
        <p class="font-sans text-sm text-[#7A7A7A] text-center">Last updated: March 2026  •  Effective date: March 2026</p>
      </div>
    </section>

    <!-- Body -->
    <section class="bg-background">
      <div class="max-w-[1440px] mx-auto px-5 sm:px-8 lg:px-20 py-10 lg:py-16">
        <div class="max-w-[720px] mx-auto flex flex-col gap-10">
          <p class="font-sans text-[15px] text-foreground" style="line-height: 1.7">
            These Terms of Service ('Terms') govern your use of the RentCred platform operated by RentCred Technologies Ltd. By accessing or using our platform, you agree to be bound by these Terms. If you do not agree, do not use the platform.
          </p>

          <div class="flex flex-col gap-4">
            <h2 class="font-mono text-xl font-semibold text-foreground">1. Definitions</h2>
            <p class="font-sans text-[15px] text-muted-foreground" style="line-height: 1.7">'Agent' refers to a registered real estate professional using the platform. 'Tenant' refers to an individual whose background is being verified. 'Report' refers to the verification document generated by RentCred.</p>
          </div>

          <div class="flex flex-col gap-4">
            <h2 class="font-mono text-xl font-semibold text-foreground">2. Account Registration and KYB</h2>
            <p class="font-sans text-[15px] text-muted-foreground" style="line-height: 1.7">All agents must complete Know Your Business (KYB) verification before submitting tenant checks. You are responsible for maintaining the confidentiality of your account credentials.</p>
          </div>

          <div class="flex flex-col gap-4">
            <h2 class="font-mono text-xl font-semibold text-foreground">3. Service Description</h2>
            <p class="font-sans text-[15px] text-muted-foreground" style="line-height: 1.7">RentCred provides tenant verification services including identity verification, employment checks, reference checks, address verification, and report generation.</p>
          </div>

          <div class="flex flex-col gap-4">
            <h2 class="font-mono text-xl font-semibold text-foreground">4. Tenant Consent</h2>
            <p class="font-sans text-[15px] text-muted-foreground" style="line-height: 1.7">Agents must obtain explicit, documented consent from tenants before submitting a verification request. RentCred may verify consent has been obtained before processing.</p>
          </div>

          <div class="flex flex-col gap-4">
            <h2 class="font-mono text-xl font-semibold text-foreground">5. Payment Terms</h2>
            <p class="font-sans text-[15px] text-muted-foreground" style="line-height: 1.7">Verification checks are paid per-check or via credit bundles. Payments are processed through Paystack. Credits are non-refundable once used. Unused bundle credits do not expire.</p>
          </div>

          <div class="flex flex-col gap-4">
            <h2 class="font-mono text-xl font-semibold text-foreground">6. SLA and Delivery</h2>
            <p class="font-sans text-[15px] text-muted-foreground" style="line-height: 1.7">Standard checks are completed within 48–72 hours. Priority bundles receive 48-hour SLA. RentCred reserves the right to extend timelines for complex verifications.</p>
          </div>

          <div class="flex flex-col gap-4">
            <h2 class="font-mono text-xl font-semibold text-foreground">7. Report Accuracy</h2>
            <p class="font-sans text-[15px] text-muted-foreground" style="line-height: 1.7">Reports are based on available data and reasonable due diligence. We do not guarantee the accuracy of third-party information. Reports represent a point-in-time assessment.</p>
          </div>

          <div class="flex flex-col gap-4">
            <h2 class="font-mono text-xl font-semibold text-foreground">8. Limitation of Liability</h2>
            <p class="font-sans text-[15px] text-muted-foreground" style="line-height: 1.7">RentCred is not liable for rental decisions made based on our reports. Our total liability shall not exceed the fees paid for the specific report in question.</p>
          </div>

          <div class="flex flex-col gap-4">
            <h2 class="font-mono text-xl font-semibold text-foreground">9. Dispute Resolution</h2>
            <p class="font-sans text-[15px] text-muted-foreground" style="line-height: 1.7">Disputes regarding report accuracy may be raised through the platform. We will investigate and respond within 7 business days. These terms are governed by the laws of the Federal Republic of Nigeria.</p>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>
